// Generado a partir del listado oficial de municipios de la provincia de Valencia.
// No editar a mano salvo correcciones puntuales — ver scripts/generate-valencia-municipalities.mjs si hace falta regenerar.

export type Municipality = {
  officialName: string
  spanishName: string
  valencianName: string
  slug: string
  province: 'Valencia'
  aliases: string[]
}

export const VALENCIA_MUNICIPALITIES: Municipality[] = [
  { officialName: 'Ademús', spanishName: 'Ademuz', valencianName: 'Ademús', slug: 'ademus', province: 'Valencia', aliases: ['Ademuz'] },
  { officialName: 'Ador', spanishName: 'Ador', valencianName: 'Ador', slug: 'ador', province: 'Valencia', aliases: [] },
  { officialName: 'Atzeneta d\'Albaida', spanishName: 'Adzaneta de Albaida', valencianName: 'Atzeneta d\'Albaida', slug: 'atzeneta-d-albaida', province: 'Valencia', aliases: ['Adzaneta de Albaida'] },
  { officialName: 'Agullent', spanishName: 'Agullent', valencianName: 'Agullent', slug: 'agullent', province: 'Valencia', aliases: [] },
  { officialName: 'Alaquàs', spanishName: 'Alacuás', valencianName: 'Alaquàs', slug: 'alaquas', province: 'Valencia', aliases: ['Alacuás'] },
  { officialName: 'Albaida', spanishName: 'Albaida', valencianName: 'Albaida', slug: 'albaida', province: 'Valencia', aliases: [] },
  { officialName: 'Albal', spanishName: 'Albal', valencianName: 'Albal', slug: 'albal', province: 'Valencia', aliases: [] },
  { officialName: 'Albalat de la Ribera', spanishName: 'Albalat de la Ribera', valencianName: 'Albalat de la Ribera', slug: 'albalat-de-la-ribera', province: 'Valencia', aliases: [] },
  { officialName: 'Albalat dels Tarongers', spanishName: 'Albalat de Taronchers', valencianName: 'Albalat dels Tarongers', slug: 'albalat-dels-tarongers', province: 'Valencia', aliases: ['Albalat de Taronchers'] },
  { officialName: 'Albalat dels Sorells', spanishName: 'Albalat dels Sorells', valencianName: 'Albalat dels Sorells', slug: 'albalat-dels-sorells', province: 'Valencia', aliases: [] },
  { officialName: 'Alberic', spanishName: 'Alberique', valencianName: 'Alberic', slug: 'alberic', province: 'Valencia', aliases: ['Alberique'] },
  { officialName: 'Alboraig', spanishName: 'Alborache', valencianName: 'Alboraig', slug: 'alboraig', province: 'Valencia', aliases: ['Alborache'] },
  { officialName: 'Alboraia', spanishName: 'Alboraya', valencianName: 'Alboraia', slug: 'alboraia', province: 'Valencia', aliases: ['Alboraya'] },
  { officialName: 'Albuixec', spanishName: 'Albuixech', valencianName: 'Albuixec', slug: 'albuixec', province: 'Valencia', aliases: ['Albuixech'] },
  { officialName: 'Alcàsser', spanishName: 'Alcácer', valencianName: 'Alcàsser', slug: 'alcasser', province: 'Valencia', aliases: ['Alcácer'] },
  { officialName: 'Alcàntera de Xúquer', spanishName: 'Alcántara de Júcar', valencianName: 'Alcàntera de Xúquer', slug: 'alcantera-de-xuquer', province: 'Valencia', aliases: ['Alcántara de Júcar'] },
  { officialName: 'Alzira', spanishName: 'Alcira', valencianName: 'Alzira', slug: 'alzira', province: 'Valencia', aliases: ['Alcira'] },
  { officialName: 'Les Alcubles', spanishName: 'Alcublas', valencianName: 'Les Alcubles', slug: 'les-alcubles', province: 'Valencia', aliases: ['Alcublas'] },
  { officialName: 'L\'Alcúdia', spanishName: 'Alcudia de Carlet', valencianName: 'L\'Alcúdia', slug: 'l-alcudia', province: 'Valencia', aliases: ['Alcudia de Carlet'] },
  { officialName: 'L\'Alcúdia de Crespìns', spanishName: 'Alcudia de Crespíns', valencianName: 'L\'Alcúdia de Crespìns', slug: 'l-alcudia-de-crespins', province: 'Valencia', aliases: ['Alcudia de Crespíns'] },
  { officialName: 'Aldaia', spanishName: 'Aldaya', valencianName: 'Aldaia', slug: 'aldaia', province: 'Valencia', aliases: ['Aldaya'] },
  { officialName: 'Alfafar', spanishName: 'Alfafar', valencianName: 'Alfafar', slug: 'alfafar', province: 'Valencia', aliases: [] },
  { officialName: 'Alfauir', spanishName: 'Alfahuir', valencianName: 'Alfauir', slug: 'alfauir', province: 'Valencia', aliases: ['Alfahuir'] },
  { officialName: 'Alfara d\'Algimia', spanishName: 'Alfara de Algimia', valencianName: 'Alfara d\'Algimia', slug: 'alfara-d-algimia', province: 'Valencia', aliases: ['Alfara de Algimia'] },
  { officialName: 'Alfara del Patriarca', spanishName: 'Alfara del Patriarca', valencianName: 'Alfara del Patriarca', slug: 'alfara-del-patriarca', province: 'Valencia', aliases: [] },
  { officialName: 'Alfarb', spanishName: 'Alfarp', valencianName: 'Alfarb', slug: 'alfarb', province: 'Valencia', aliases: ['Alfarp'] },
  { officialName: 'Alfarrassí', spanishName: 'Alfarrasí', valencianName: 'Alfarrassí', slug: 'alfarrassi', province: 'Valencia', aliases: ['Alfarrasí'] },
  { officialName: 'Algar', spanishName: 'Algar de Palancia', valencianName: 'Algar', slug: 'algar', province: 'Valencia', aliases: ['Algar de Palancia'] },
  { officialName: 'Algemesí', spanishName: 'Algemesí', valencianName: 'Algemesí', slug: 'algemesi', province: 'Valencia', aliases: [] },
  { officialName: 'Algimia de la Baronia', spanishName: 'Algimia de Alfara', valencianName: 'Algimia de la Baronia', slug: 'algimia-de-la-baronia', province: 'Valencia', aliases: ['Algimia de Alfara'] },
  { officialName: 'Alginet', spanishName: 'Alginet', valencianName: 'Alginet', slug: 'alginet', province: 'Valencia', aliases: [] },
  { officialName: 'Almàssera', spanishName: 'Almácera', valencianName: 'Almàssera', slug: 'almassera', province: 'Valencia', aliases: ['Almácera'] },
  { officialName: 'Almiserà', spanishName: 'Almiserat', valencianName: 'Almiserà', slug: 'almisera', province: 'Valencia', aliases: ['Almiserat'] },
  { officialName: 'Almoines', spanishName: 'Almoines', valencianName: 'Almoines', slug: 'almoines', province: 'Valencia', aliases: [] },
  { officialName: 'Almussafes', spanishName: 'Almusafes', valencianName: 'Almussafes', slug: 'almussafes', province: 'Valencia', aliases: ['Almusafes'] },
  { officialName: 'Alpont', spanishName: 'Alpuente', valencianName: 'Alpont', slug: 'alpont', province: 'Valencia', aliases: ['Alpuente'] },
  { officialName: 'L\'Alqueria de la Comtessa', spanishName: 'Alquería de la Condesa', valencianName: 'L\'Alqueria de la Comtessa', slug: 'l-alqueria-de-la-comtessa', province: 'Valencia', aliases: ['Alquería de la Condesa'] },
  { officialName: 'Andilla', spanishName: 'Andilla', valencianName: 'Andilla', slug: 'andilla', province: 'Valencia', aliases: [] },
  { officialName: 'Anna', spanishName: 'Anna', valencianName: 'Anna', slug: 'anna', province: 'Valencia', aliases: [] },
  { officialName: 'Antella', spanishName: 'Antella', valencianName: 'Antella', slug: 'antella', province: 'Valencia', aliases: [] },
  { officialName: 'Ares d\'Alpont', spanishName: 'Aras de los Olmos', valencianName: 'Ares d\'Alpont', slug: 'ares-d-alpont', province: 'Valencia', aliases: ['Aras de los Olmos'] },
  { officialName: 'Aielo de Malferit', spanishName: 'Ayelo de Malferit', valencianName: 'Aielo de Malferit', slug: 'aielo-de-malferit', province: 'Valencia', aliases: ['Ayelo de Malferit'] },
  { officialName: 'Aielo de Rugat', spanishName: 'Ayelo de Rugat', valencianName: 'Aielo de Rugat', slug: 'aielo-de-rugat', province: 'Valencia', aliases: ['Ayelo de Rugat'] },
  { officialName: 'Aiora', spanishName: 'Ayora', valencianName: 'Aiora', slug: 'aiora', province: 'Valencia', aliases: ['Ayora'] },
  { officialName: 'Barxeta', spanishName: 'Barcheta', valencianName: 'Barxeta', slug: 'barxeta', province: 'Valencia', aliases: ['Barcheta'] },
  { officialName: 'Barx', spanishName: 'Bárig', valencianName: 'Barx', slug: 'barx', province: 'Valencia', aliases: ['Bárig'] },
  { officialName: 'Bèlgida', spanishName: 'Bélgida', valencianName: 'Bèlgida', slug: 'belgida', province: 'Valencia', aliases: ['Bélgida'] },
  { officialName: 'Bellreguard', spanishName: 'Bellreguart', valencianName: 'Bellreguard', slug: 'bellreguard', province: 'Valencia', aliases: ['Bellreguart'] },
  { officialName: 'Bellús', spanishName: 'Bellús', valencianName: 'Bellús', slug: 'bellus', province: 'Valencia', aliases: [] },
  { officialName: 'Benaixeve', spanishName: 'Benagéber', valencianName: 'Benaixeve', slug: 'benaixeve', province: 'Valencia', aliases: ['Benagéber'] },
  { officialName: 'Benaguasil', spanishName: 'Benaguacil', valencianName: 'Benaguasil', slug: 'benaguasil', province: 'Valencia', aliases: ['Benaguacil'] },
  { officialName: 'Benavites', spanishName: 'Benavites', valencianName: 'Benavites', slug: 'benavites', province: 'Valencia', aliases: [] },
  { officialName: 'Beneixida', spanishName: 'Benegida', valencianName: 'Beneixida', slug: 'beneixida', province: 'Valencia', aliases: ['Benegida'] },
  { officialName: 'Benetússer', spanishName: 'Benetúser', valencianName: 'Benetússer', slug: 'benetusser', province: 'Valencia', aliases: ['Benetúser'] },
  { officialName: 'Beniarjó', spanishName: 'Beniarjó', valencianName: 'Beniarjó', slug: 'beniarjo', province: 'Valencia', aliases: [] },
  { officialName: 'Beniatjar', spanishName: 'Beniatjar', valencianName: 'Beniatjar', slug: 'beniatjar', province: 'Valencia', aliases: [] },
  { officialName: 'Benicolet', spanishName: 'Benicolet', valencianName: 'Benicolet', slug: 'benicolet', province: 'Valencia', aliases: [] },
  { officialName: 'Benicull de Xúquer', spanishName: 'Benicull de Júcar', valencianName: 'Benicull de Xúquer', slug: 'benicull-de-xuquer', province: 'Valencia', aliases: ['Benicull de Júcar'] },
  { officialName: 'Benifairó de la Valldigna', spanishName: 'Benifairó de la Valldigna', valencianName: 'Benifairó de la Valldigna', slug: 'benifairo-de-la-valldigna', province: 'Valencia', aliases: [] },
  { officialName: 'Benifairó de les Valls', spanishName: 'Benifairó de los Valles', valencianName: 'Benifairó de les Valls', slug: 'benifairo-de-les-valls', province: 'Valencia', aliases: ['Benifairó de los Valles'] },
  { officialName: 'Benifaió', spanishName: 'Benifayó', valencianName: 'Benifaió', slug: 'benifaio', province: 'Valencia', aliases: ['Benifayó'] },
  { officialName: 'Beniflà', spanishName: 'Beniflá', valencianName: 'Beniflà', slug: 'benifla', province: 'Valencia', aliases: ['Beniflá'] },
  { officialName: 'Benigànim', spanishName: 'Benigánim', valencianName: 'Benigànim', slug: 'beniganim', province: 'Valencia', aliases: ['Benigánim'] },
  { officialName: 'Benimodo', spanishName: 'Benimodo', valencianName: 'Benimodo', slug: 'benimodo', province: 'Valencia', aliases: [] },
  { officialName: 'Benimuslem', spanishName: 'Benimuslem', valencianName: 'Benimuslem', slug: 'benimuslem', province: 'Valencia', aliases: [] },
  { officialName: 'Beniparrell', spanishName: 'Beniparrell', valencianName: 'Beniparrell', slug: 'beniparrell', province: 'Valencia', aliases: [] },
  { officialName: 'Benirredrà', spanishName: 'Benirredrá', valencianName: 'Benirredrà', slug: 'benirredra', province: 'Valencia', aliases: ['Benirredrá'] },
  { officialName: 'Benissanó', spanishName: 'Benisanó', valencianName: 'Benissanó', slug: 'benissano', province: 'Valencia', aliases: ['Benisanó'] },
  { officialName: 'Benissoda', spanishName: 'Benisoda', valencianName: 'Benissoda', slug: 'benissoda', province: 'Valencia', aliases: ['Benisoda'] },
  { officialName: 'Benissuera', spanishName: 'Benisuera', valencianName: 'Benissuera', slug: 'benissuera', province: 'Valencia', aliases: ['Benisuera'] },
  { officialName: 'Bétera', spanishName: 'Bétera', valencianName: 'Bétera', slug: 'betera', province: 'Valencia', aliases: [] },
  { officialName: 'Bicorb', spanishName: 'Bicorp', valencianName: 'Bicorb', slug: 'bicorb', province: 'Valencia', aliases: ['Bicorp'] },
  { officialName: 'Bocairent', spanishName: 'Bocairente', valencianName: 'Bocairent', slug: 'bocairent', province: 'Valencia', aliases: ['Bocairente'] },
  { officialName: 'Bolbait', spanishName: 'Bolbaite', valencianName: 'Bolbait', slug: 'bolbait', province: 'Valencia', aliases: ['Bolbaite'] },
  { officialName: 'Bonrepòs i Mirambell', spanishName: 'Bonrepós y Mirambell', valencianName: 'Bonrepòs i Mirambell', slug: 'bonrepos-i-mirambell', province: 'Valencia', aliases: ['Bonrepós y Mirambell'] },
  { officialName: 'Bufali', spanishName: 'Bufali', valencianName: 'Bufali', slug: 'bufali', province: 'Valencia', aliases: [] },
  { officialName: 'Bugarra', spanishName: 'Bugarra', valencianName: 'Bugarra', slug: 'bugarra', province: 'Valencia', aliases: [] },
  { officialName: 'Bunyol', spanishName: 'Buñol', valencianName: 'Bunyol', slug: 'bunyol', province: 'Valencia', aliases: ['Buñol'] },
  { officialName: 'Burjassot', spanishName: 'Burjasot', valencianName: 'Burjassot', slug: 'burjassot', province: 'Valencia', aliases: ['Burjasot'] },
  { officialName: 'Calles', spanishName: 'Calles', valencianName: 'Calles', slug: 'calles', province: 'Valencia', aliases: [] },
  { officialName: 'Camporrobles', spanishName: 'Camporrobles', valencianName: 'Camporrobles', slug: 'camporrobles', province: 'Valencia', aliases: [] },
  { officialName: 'Canals', spanishName: 'Canals', valencianName: 'Canals', slug: 'canals', province: 'Valencia', aliases: [] },
  { officialName: 'Canet d\'En Berenguer', spanishName: 'Canet de Berenguer', valencianName: 'Canet d\'En Berenguer', slug: 'canet-d-en-berenguer', province: 'Valencia', aliases: ['Canet de Berenguer'] },
  { officialName: 'Carcaixent', spanishName: 'Carcagente', valencianName: 'Carcaixent', slug: 'carcaixent', province: 'Valencia', aliases: ['Carcagente'] },
  { officialName: 'Càrcer', spanishName: 'Cárcer', valencianName: 'Càrcer', slug: 'carcer', province: 'Valencia', aliases: ['Cárcer'] },
  { officialName: 'Carlet', spanishName: 'Carlet', valencianName: 'Carlet', slug: 'carlet', province: 'Valencia', aliases: [] },
  { officialName: 'Carrícola', spanishName: 'Carrícola', valencianName: 'Carrícola', slug: 'carricola', province: 'Valencia', aliases: [] },
  { officialName: 'Casas Altas', spanishName: 'Casas Altas', valencianName: 'Casas Altas', slug: 'casas-altas', province: 'Valencia', aliases: [] },
  { officialName: 'Casas Bajas', spanishName: 'Casas Bajas', valencianName: 'Casas Bajas', slug: 'casas-bajas', province: 'Valencia', aliases: [] },
  { officialName: 'Casinos', spanishName: 'Casinos', valencianName: 'Casinos', slug: 'casinos', province: 'Valencia', aliases: [] },
  { officialName: 'Castelló de Rugat', spanishName: 'Castellón de Rugat', valencianName: 'Castelló de Rugat', slug: 'castello-de-rugat', province: 'Valencia', aliases: ['Castellón de Rugat'] },
  { officialName: 'Castellonet de la Conquesta', spanishName: 'Castellonet', valencianName: 'Castellonet de la Conquesta', slug: 'castellonet-de-la-conquesta', province: 'Valencia', aliases: ['Castellonet'] },
  { officialName: 'Castellfabib', spanishName: 'Castielfabib', valencianName: 'Castellfabib', slug: 'castellfabib', province: 'Valencia', aliases: ['Castielfabib'] },
  { officialName: 'Catadau', spanishName: 'Catadau', valencianName: 'Catadau', slug: 'catadau', province: 'Valencia', aliases: [] },
  { officialName: 'Catarroja', spanishName: 'Catarroja', valencianName: 'Catarroja', slug: 'catarroja', province: 'Valencia', aliases: [] },
  { officialName: 'Caudete de las Fuentes', spanishName: 'Caudete de las Fuentes', valencianName: 'Caudete de las Fuentes', slug: 'caudete-de-las-fuentes', province: 'Valencia', aliases: [] },
  { officialName: 'Cerdà', spanishName: 'Cerdá', valencianName: 'Cerdà', slug: 'cerda', province: 'Valencia', aliases: ['Cerdá'] },
  { officialName: 'Xella', spanishName: 'Chella', valencianName: 'Xella', slug: 'xella', province: 'Valencia', aliases: ['Chella'] },
  { officialName: 'Xelva', spanishName: 'Chelva', valencianName: 'Xelva', slug: 'xelva', province: 'Valencia', aliases: ['Chelva'] },
  { officialName: 'Xera', spanishName: 'Chera', valencianName: 'Xera', slug: 'xera', province: 'Valencia', aliases: ['Chera'] },
  { officialName: 'Xest', spanishName: 'Cheste', valencianName: 'Xest', slug: 'xest', province: 'Valencia', aliases: ['Cheste'] },
  { officialName: 'Xirivella', spanishName: 'Chirivella', valencianName: 'Xirivella', slug: 'xirivella', province: 'Valencia', aliases: ['Chirivella'] },
  { officialName: 'Xiva', spanishName: 'Chiva', valencianName: 'Xiva', slug: 'xiva', province: 'Valencia', aliases: ['Chiva'] },
  { officialName: 'Xulella', spanishName: 'Chulilla', valencianName: 'Xulella', slug: 'xulella', province: 'Valencia', aliases: ['Chulilla'] },
  { officialName: 'Cofrents', spanishName: 'Cofrentes', valencianName: 'Cofrents', slug: 'cofrents', province: 'Valencia', aliases: ['Cofrentes'] },
  { officialName: 'Corbera', spanishName: 'Corbera', valencianName: 'Corbera', slug: 'corbera', province: 'Valencia', aliases: [] },
  { officialName: 'Cortes de Pallars', spanishName: 'Cortes de Pallás', valencianName: 'Cortes de Pallars', slug: 'cortes-de-pallars', province: 'Valencia', aliases: ['Cortes de Pallás'] },
  { officialName: 'Cotes', spanishName: 'Cotes', valencianName: 'Cotes', slug: 'cotes', province: 'Valencia', aliases: [] },
  { officialName: 'Quart de les Valls', spanishName: 'Cuart de les Valls', valencianName: 'Quart de les Valls', slug: 'quart-de-les-valls', province: 'Valencia', aliases: ['Cuart de les Valls'] },
  { officialName: 'Quart de Poblet', spanishName: 'Cuart de Poblet', valencianName: 'Quart de Poblet', slug: 'quart-de-poblet', province: 'Valencia', aliases: ['Cuart de Poblet'] },
  { officialName: 'Quartell', spanishName: 'Cuartell', valencianName: 'Quartell', slug: 'quartell', province: 'Valencia', aliases: ['Cuartell'] },
  { officialName: 'Quatretonda', spanishName: 'Cuatretonda', valencianName: 'Quatretonda', slug: 'quatretonda', province: 'Valencia', aliases: ['Cuatretonda'] },
  { officialName: 'Cullera', spanishName: 'Cullera', valencianName: 'Cullera', slug: 'cullera', province: 'Valencia', aliases: [] },
  { officialName: 'Daimús', spanishName: 'Daimuz', valencianName: 'Daimús', slug: 'daimus', province: 'Valencia', aliases: ['Daimuz'] },
  { officialName: 'Domenyo', spanishName: 'Domeño', valencianName: 'Domenyo', slug: 'domenyo', province: 'Valencia', aliases: ['Domeño'] },
  { officialName: 'Dosaigües', spanishName: 'Dos Aguas', valencianName: 'Dosaigües', slug: 'dosaigues', province: 'Valencia', aliases: ['Dos Aguas'] },
  { officialName: 'L\'Eliana', spanishName: 'La Eliana', valencianName: 'L\'Eliana', slug: 'l-eliana', province: 'Valencia', aliases: ['La Eliana'] },
  { officialName: 'Emperador', spanishName: 'Emperador', valencianName: 'Emperador', slug: 'emperador', province: 'Valencia', aliases: [] },
  { officialName: 'Ènguera', spanishName: 'Enguera', valencianName: 'Ènguera', slug: 'enguera', province: 'Valencia', aliases: ['Enguera'] },
  { officialName: 'L\'Ènova', spanishName: 'Énova', valencianName: 'L\'Ènova', slug: 'l-enova', province: 'Valencia', aliases: ['Énova'] },
  { officialName: 'Estivella', spanishName: 'Estivella', valencianName: 'Estivella', slug: 'estivella', province: 'Valencia', aliases: [] },
  { officialName: 'Estubeny', spanishName: 'Estubeny', valencianName: 'Estubeny', slug: 'estubeny', province: 'Valencia', aliases: [] },
  { officialName: 'Faura', spanishName: 'Faura', valencianName: 'Faura', slug: 'faura', province: 'Valencia', aliases: [] },
  { officialName: 'Favara', spanishName: 'Favareta', valencianName: 'Favara', slug: 'favara', province: 'Valencia', aliases: ['Favareta'] },
  { officialName: 'Fontanars dels Alforins', spanishName: 'Fontanares', valencianName: 'Fontanars dels Alforins', slug: 'fontanars-dels-alforins', province: 'Valencia', aliases: ['Fontanares'] },
  { officialName: 'Fortaleny', spanishName: 'Fortaleny', valencianName: 'Fortaleny', slug: 'fortaleny', province: 'Valencia', aliases: [] },
  { officialName: 'Foios', spanishName: 'Foyos', valencianName: 'Foios', slug: 'foios', province: 'Valencia', aliases: ['Foyos'] },
  { officialName: 'La Font d\'En Carròs', spanishName: 'Fuente Encarroz', valencianName: 'La Font d\'En Carròs', slug: 'la-font-d-en-carros', province: 'Valencia', aliases: ['Fuente Encarroz'] },
  { officialName: 'La Font de la Figuera', spanishName: 'Fuente la Higuera', valencianName: 'La Font de la Figuera', slug: 'la-font-de-la-figuera', province: 'Valencia', aliases: ['Fuente la Higuera'] },
  { officialName: 'Fuenterrobles', spanishName: 'Fuenterrobles', valencianName: 'Fuenterrobles', slug: 'fuenterrobles', province: 'Valencia', aliases: [] },
  { officialName: 'Gavarda', spanishName: 'Gabarda', valencianName: 'Gavarda', slug: 'gavarda', province: 'Valencia', aliases: ['Gabarda'] },
  { officialName: 'Gandia', spanishName: 'Gandía', valencianName: 'Gandia', slug: 'gandia', province: 'Valencia', aliases: ['Gandía'] },
  { officialName: 'Gàtova', spanishName: 'Gátova', valencianName: 'Gàtova', slug: 'gatova', province: 'Valencia', aliases: ['Gátova'] },
  { officialName: 'Genovés', spanishName: 'Genovés', valencianName: 'Genovés', slug: 'genoves', province: 'Valencia', aliases: [] },
  { officialName: 'Xestalgar', spanishName: 'Gestalgar', valencianName: 'Xestalgar', slug: 'xestalgar', province: 'Valencia', aliases: ['Gestalgar'] },
  { officialName: 'Gilet', spanishName: 'Gilet', valencianName: 'Gilet', slug: 'gilet', province: 'Valencia', aliases: [] },
  { officialName: 'Godella', spanishName: 'Godella', valencianName: 'Godella', slug: 'godella', province: 'Valencia', aliases: [] },
  { officialName: 'Godelleta', spanishName: 'Godelleta', valencianName: 'Godelleta', slug: 'godelleta', province: 'Valencia', aliases: [] },
  { officialName: 'La Granja de la Costera', spanishName: 'La Granja de la Costera', valencianName: 'La Granja de la Costera', slug: 'la-granja-de-la-costera', province: 'Valencia', aliases: [] },
  { officialName: 'Guadassèquies', spanishName: 'Guadasequies', valencianName: 'Guadassèquies', slug: 'guadassequies', province: 'Valencia', aliases: ['Guadasequies'] },
  { officialName: 'Guadassuar', spanishName: 'Guadasuar', valencianName: 'Guadassuar', slug: 'guadassuar', province: 'Valencia', aliases: ['Guadasuar'] },
  { officialName: 'Guardamar de la Safor', spanishName: 'Guardamar', valencianName: 'Guardamar de la Safor', slug: 'guardamar-de-la-safor', province: 'Valencia', aliases: ['Guardamar'] },
  { officialName: 'Figueroles', spanishName: 'Higueruelas', valencianName: 'Figueroles', slug: 'figueroles', province: 'Valencia', aliases: ['Higueruelas'] },
  { officialName: 'Xalans', spanishName: 'Jalance', valencianName: 'Xalans', slug: 'xalans', province: 'Valencia', aliases: ['Jalance'] },
  { officialName: 'Xeraco', spanishName: 'Jaraco', valencianName: 'Xeraco', slug: 'xeraco', province: 'Valencia', aliases: ['Jaraco'] },
  { officialName: 'Xarafull', spanishName: 'Jarafuel', valencianName: 'Xarafull', slug: 'xarafull', province: 'Valencia', aliases: ['Jarafuel'] },
  { officialName: 'Xàtiva', spanishName: 'Játiva', valencianName: 'Xàtiva', slug: 'xativa', province: 'Valencia', aliases: ['Játiva', 'Xátiva'] },
  { officialName: 'Xeresa', spanishName: 'Jeresa', valencianName: 'Xeresa', slug: 'xeresa', province: 'Valencia', aliases: ['Jeresa'] },
  { officialName: 'Llíria', spanishName: 'Liria', valencianName: 'Llíria', slug: 'lliria', province: 'Valencia', aliases: ['Liria'] },
  { officialName: 'Llanera de Ranes', spanishName: 'Llanera de Ranes', valencianName: 'Llanera de Ranes', slug: 'llanera-de-ranes', province: 'Valencia', aliases: [] },
  { officialName: 'Llaurí', spanishName: 'Llaurí', valencianName: 'Llaurí', slug: 'llauri', province: 'Valencia', aliases: [] },
  { officialName: 'Llombai', spanishName: 'Llombay', valencianName: 'Llombai', slug: 'llombai', province: 'Valencia', aliases: ['Llombay'] },
  { officialName: 'La Llosa de Ranes', spanishName: 'Llosa de Ranes', valencianName: 'La Llosa de Ranes', slug: 'la-llosa-de-ranes', province: 'Valencia', aliases: ['Llosa de Ranes'] },
  { officialName: 'Loriguilla', spanishName: 'Loriguilla', valencianName: 'Loriguilla', slug: 'loriguilla', province: 'Valencia', aliases: [] },
  { officialName: 'Llosa del Bisbe', spanishName: 'Losa del Obispo', valencianName: 'Llosa del Bisbe', slug: 'llosa-del-bisbe', province: 'Valencia', aliases: ['Losa del Obispo'] },
  { officialName: 'Llutxent', spanishName: 'Luchente', valencianName: 'Llutxent', slug: 'llutxent', province: 'Valencia', aliases: ['Luchente'] },
  { officialName: 'Llocnou d\'En Fenollet', spanishName: 'Lugar Nuevo de Fenollet', valencianName: 'Llocnou d\'En Fenollet', slug: 'llocnou-d-en-fenollet', province: 'Valencia', aliases: ['Lugar Nuevo de Fenollet'] },
  { officialName: 'Poblenou de la Corona', spanishName: 'Lugar Nuevo de la Corona', valencianName: 'Poblenou de la Corona', slug: 'poblenou-de-la-corona', province: 'Valencia', aliases: ['Lugar Nuevo de la Corona'] },
  { officialName: 'Llocnou de Sant Jeroni', spanishName: 'Lugar Nuevo de San Jerónimo', valencianName: 'Llocnou de Sant Jeroni', slug: 'llocnou-de-sant-jeroni', province: 'Valencia', aliases: ['Lugar Nuevo de San Jerónimo'] },
  { officialName: 'Macastre', spanishName: 'Macastre', valencianName: 'Macastre', slug: 'macastre', province: 'Valencia', aliases: [] },
  { officialName: 'Manises', spanishName: 'Manises', valencianName: 'Manises', slug: 'manises', province: 'Valencia', aliases: [] },
  { officialName: 'Manuel', spanishName: 'Manuel', valencianName: 'Manuel', slug: 'manuel', province: 'Valencia', aliases: [] },
  { officialName: 'Marines', spanishName: 'Marines', valencianName: 'Marines', slug: 'marines', province: 'Valencia', aliases: [] },
  { officialName: 'Massalavés', spanishName: 'Masalavés', valencianName: 'Massalavés', slug: 'massalaves', province: 'Valencia', aliases: ['Masalavés'] },
  { officialName: 'Massalfassar', spanishName: 'Masalfasar', valencianName: 'Massalfassar', slug: 'massalfassar', province: 'Valencia', aliases: ['Masalfasar'] },
  { officialName: 'Massamagrell', spanishName: 'Masamagrell', valencianName: 'Massamagrell', slug: 'massamagrell', province: 'Valencia', aliases: ['Masamagrell'] },
  { officialName: 'Massanassa', spanishName: 'Masanasa', valencianName: 'Massanassa', slug: 'massanassa', province: 'Valencia', aliases: ['Masanasa'] },
  { officialName: 'Meliana', spanishName: 'Meliana', valencianName: 'Meliana', slug: 'meliana', province: 'Valencia', aliases: [] },
  { officialName: 'Millars', spanishName: 'Millares', valencianName: 'Millars', slug: 'millars', province: 'Valencia', aliases: ['Millares'] },
  { officialName: 'Miramar', spanishName: 'Miramar', valencianName: 'Miramar', slug: 'miramar', province: 'Valencia', aliases: [] },
  { officialName: 'Mislata', spanishName: 'Mislata', valencianName: 'Mislata', slug: 'mislata', province: 'Valencia', aliases: [] },
  { officialName: 'Moixent', spanishName: 'Mogente', valencianName: 'Moixent', slug: 'moixent', province: 'Valencia', aliases: ['Mogente'] },
  { officialName: 'Montcada', spanishName: 'Moncada', valencianName: 'Montcada', slug: 'montcada', province: 'Valencia', aliases: ['Moncada'] },
  { officialName: 'Montserrat d\'Alcalà', spanishName: 'Monserrat', valencianName: 'Montserrat d\'Alcalà', slug: 'montserrat-d-alcala', province: 'Valencia', aliases: ['Monserrat', 'Montserrat'] },
  { officialName: 'Montaverner', spanishName: 'Montaverner', valencianName: 'Montaverner', slug: 'montaverner', province: 'Valencia', aliases: [] },
  { officialName: 'Montesa', spanishName: 'Montesa', valencianName: 'Montesa', slug: 'montesa', province: 'Valencia', aliases: [] },
  { officialName: 'Montixelvo', spanishName: 'Montichelvo', valencianName: 'Montixelvo', slug: 'montixelvo', province: 'Valencia', aliases: ['Montichelvo'] },
  { officialName: 'Montroi', spanishName: 'Montroy', valencianName: 'Montroi', slug: 'montroi', province: 'Valencia', aliases: ['Montroy'] },
  { officialName: 'Museros', spanishName: 'Museros', valencianName: 'Museros', slug: 'museros', province: 'Valencia', aliases: [] },
  { officialName: 'Nàquera', spanishName: 'Náquera', valencianName: 'Nàquera', slug: 'naquera', province: 'Valencia', aliases: ['Náquera'] },
  { officialName: 'Navarrés', spanishName: 'Navarrés', valencianName: 'Navarrés', slug: 'navarres', province: 'Valencia', aliases: [] },
  { officialName: 'Novetlè', spanishName: 'Novelé', valencianName: 'Novetlè', slug: 'novetle', province: 'Valencia', aliases: ['Novelé'] },
  { officialName: 'Oliva', spanishName: 'Oliva', valencianName: 'Oliva', slug: 'oliva', province: 'Valencia', aliases: [] },
  { officialName: 'L\'Olleria', spanishName: 'Ollería', valencianName: 'L\'Olleria', slug: 'l-olleria', province: 'Valencia', aliases: ['Ollería'] },
  { officialName: 'Olocau', spanishName: 'Olocau', valencianName: 'Olocau', slug: 'olocau', province: 'Valencia', aliases: [] },
  { officialName: 'Ontinyent', spanishName: 'Onteniente', valencianName: 'Ontinyent', slug: 'ontinyent', province: 'Valencia', aliases: ['Onteniente'] },
  { officialName: 'Otos', spanishName: 'Otos', valencianName: 'Otos', slug: 'otos', province: 'Valencia', aliases: [] },
  { officialName: 'Paiporta', spanishName: 'Paiporta', valencianName: 'Paiporta', slug: 'paiporta', province: 'Valencia', aliases: [] },
  { officialName: 'Palma de Gandia', spanishName: 'Palma de Gandía', valencianName: 'Palma de Gandia', slug: 'palma-de-gandia', province: 'Valencia', aliases: ['Palma de Gandía'] },
  { officialName: 'Palomar', spanishName: 'Palomar', valencianName: 'Palomar', slug: 'palomar', province: 'Valencia', aliases: ['El Palomar'] },
  { officialName: 'Paterna', spanishName: 'Paterna', valencianName: 'Paterna', slug: 'paterna', province: 'Valencia', aliases: [] },
  { officialName: 'Pedralba', spanishName: 'Pedralba', valencianName: 'Pedralba', slug: 'pedralba', province: 'Valencia', aliases: [] },
  { officialName: 'Petrés', spanishName: 'Petrés', valencianName: 'Petrés', slug: 'petres', province: 'Valencia', aliases: [] },
  { officialName: 'Picanya', spanishName: 'Picaña', valencianName: 'Picanya', slug: 'picanya', province: 'Valencia', aliases: ['Picaña'] },
  { officialName: 'Picassent', spanishName: 'Picasent', valencianName: 'Picassent', slug: 'picassent', province: 'Valencia', aliases: ['Picasent'] },
  { officialName: 'Piles', spanishName: 'Piles', valencianName: 'Piles', slug: 'piles', province: 'Valencia', aliases: [] },
  { officialName: 'Pinet', spanishName: 'Pinet', valencianName: 'Pinet', slug: 'pinet', province: 'Valencia', aliases: [] },
  { officialName: 'Polinyà de Xúquer', spanishName: 'Poliñá de Júcar', valencianName: 'Polinyà de Xúquer', slug: 'polinya-de-xuquer', province: 'Valencia', aliases: ['Poliñá de Júcar'] },
  { officialName: 'Potries', spanishName: 'Potríes', valencianName: 'Potries', slug: 'potries', province: 'Valencia', aliases: ['Potríes'] },
  { officialName: 'Pobla de Farnals', spanishName: 'Puebla de Farnáls', valencianName: 'Pobla de Farnals', slug: 'pobla-de-farnals', province: 'Valencia', aliases: ['Puebla de Farnáls', 'La Pobla de Farnals'] },
  { officialName: 'La Pobla de Sant Miquel', spanishName: 'Puebla de San Miguel', valencianName: 'La Pobla de Sant Miquel', slug: 'la-pobla-de-sant-miquel', province: 'Valencia', aliases: ['Puebla de San Miguel'] },
  { officialName: 'La Pobla de Vallbona', spanishName: 'Puebla de Vallbona', valencianName: 'La Pobla de Vallbona', slug: 'la-pobla-de-vallbona', province: 'Valencia', aliases: ['Puebla de Vallbona'] },
  { officialName: 'La Pobla del Duc', spanishName: 'Puebla del Duc', valencianName: 'La Pobla del Duc', slug: 'la-pobla-del-duc', province: 'Valencia', aliases: ['Puebla del Duc'] },
  { officialName: 'La Pobla Llarga', spanishName: 'Puebla Larga', valencianName: 'La Pobla Llarga', slug: 'la-pobla-llarga', province: 'Valencia', aliases: ['Puebla Larga'] },
  { officialName: 'Puig', spanishName: 'Puig', valencianName: 'Puig', slug: 'puig', province: 'Valencia', aliases: ['El Puig'] },
  { officialName: 'Puçol', spanishName: 'Puzol', valencianName: 'Puçol', slug: 'pucol', province: 'Valencia', aliases: ['Puzol'] },
  { officialName: 'Quesa', spanishName: 'Quesa', valencianName: 'Quesa', slug: 'quesa', province: 'Valencia', aliases: [] },
  { officialName: 'Rafelbunyol', spanishName: 'Rafelbuñol', valencianName: 'Rafelbunyol', slug: 'rafelbunyol', province: 'Valencia', aliases: ['Rafelbuñol'] },
  { officialName: 'Rafelcofer', spanishName: 'Rafelcofer', valencianName: 'Rafelcofer', slug: 'rafelcofer', province: 'Valencia', aliases: [] },
  { officialName: 'Rafelguaraf', spanishName: 'Rafelguaraf', valencianName: 'Rafelguaraf', slug: 'rafelguaraf', province: 'Valencia', aliases: [] },
  { officialName: 'El Ràfol de Salem', spanishName: 'Ráfol de Salem', valencianName: 'El Ràfol de Salem', slug: 'el-rafol-de-salem', province: 'Valencia', aliases: ['Ráfol de Salem'] },
  { officialName: 'Real de Gandia', spanishName: 'Real de Gandía', valencianName: 'Real de Gandia', slug: 'real-de-gandia', province: 'Valencia', aliases: ['Real de Gandía'] },
  { officialName: 'Real de Montroi', spanishName: 'Real de Montroy', valencianName: 'Real de Montroi', slug: 'real-de-montroi', province: 'Valencia', aliases: ['Real de Montroy'] },
  { officialName: 'Requena', spanishName: 'Requena', valencianName: 'Requena', slug: 'requena', province: 'Valencia', aliases: [] },
  { officialName: 'Riba-roja de Túria', spanishName: 'Ribarroja del Turia', valencianName: 'Riba-roja de Túria', slug: 'riba-roja-de-turia', province: 'Valencia', aliases: ['Ribarroja del Turia'] },
  { officialName: 'Riola', spanishName: 'Riola', valencianName: 'Riola', slug: 'riola', province: 'Valencia', aliases: [] },
  { officialName: 'Rocafort', spanishName: 'Rocafort', valencianName: 'Rocafort', slug: 'rocafort', province: 'Valencia', aliases: [] },
  { officialName: 'Rotglà i Corberà', spanishName: 'Rotglá y Corbera', valencianName: 'Rotglà i Corberà', slug: 'rotgla-i-corbera', province: 'Valencia', aliases: ['Rotglá y Corbera'] },
  { officialName: 'Ròtova', spanishName: 'Rótova', valencianName: 'Ròtova', slug: 'rotova', province: 'Valencia', aliases: ['Rótova'] },
  { officialName: 'Rugat', spanishName: 'Rugat', valencianName: 'Rugat', slug: 'rugat', province: 'Valencia', aliases: [] },
  { officialName: 'Sagunt', spanishName: 'Sagunto', valencianName: 'Sagunt', slug: 'sagunt', province: 'Valencia', aliases: ['Sagunto'] },
  { officialName: 'Salem', spanishName: 'Salem', valencianName: 'Salem', slug: 'salem', province: 'Valencia', aliases: [] },
  { officialName: 'Sant Antoni de Benaixeve', spanishName: 'San Antonio de Benagéber', valencianName: 'Sant Antoni de Benaixeve', slug: 'sant-antoni-de-benaixeve', province: 'Valencia', aliases: ['San Antonio de Benagéber'] },
  { officialName: 'Sant Joan de l\'Ènova', spanishName: 'San Juan de Énova', valencianName: 'Sant Joan de l\'Ènova', slug: 'sant-joan-de-l-enova', province: 'Valencia', aliases: ['San Juan de Énova'] },
  { officialName: 'Sedaví', spanishName: 'Sedaví', valencianName: 'Sedaví', slug: 'sedavi', province: 'Valencia', aliases: [] },
  { officialName: 'Segart', spanishName: 'Segart', valencianName: 'Segart', slug: 'segart', province: 'Valencia', aliases: [] },
  { officialName: 'Sellent', spanishName: 'Sellent', valencianName: 'Sellent', slug: 'sellent', province: 'Valencia', aliases: [] },
  { officialName: 'Sant Pere', spanishName: 'Sempere', valencianName: 'Sant Pere', slug: 'sant-pere', province: 'Valencia', aliases: ['Sempere'] },
  { officialName: 'Senyera', spanishName: 'Señera', valencianName: 'Senyera', slug: 'senyera', province: 'Valencia', aliases: ['Señera'] },
  { officialName: 'Serra', spanishName: 'Serra', valencianName: 'Serra', slug: 'serra', province: 'Valencia', aliases: [] },
  { officialName: 'Setaigües', spanishName: 'Siete Aguas', valencianName: 'Setaigües', slug: 'setaigues', province: 'Valencia', aliases: ['Siete Aguas'] },
  { officialName: 'Silla', spanishName: 'Silla', valencianName: 'Silla', slug: 'silla', province: 'Valencia', aliases: [] },
  { officialName: 'Simat de la Valldigna', spanishName: 'Simat de Valldigna', valencianName: 'Simat de la Valldigna', slug: 'simat-de-la-valldigna', province: 'Valencia', aliases: ['Simat de Valldigna'] },
  { officialName: 'Sinarques', spanishName: 'Sinarcas', valencianName: 'Sinarques', slug: 'sinarques', province: 'Valencia', aliases: ['Sinarcas'] },
  { officialName: 'Sollana', spanishName: 'Sollana', valencianName: 'Sollana', slug: 'sollana', province: 'Valencia', aliases: [] },
  { officialName: 'Sot de Xera', spanishName: 'Sot de Chera', valencianName: 'Sot de Xera', slug: 'sot-de-xera', province: 'Valencia', aliases: ['Sot de Chera'] },
  { officialName: 'Sueca', spanishName: 'Sueca', valencianName: 'Sueca', slug: 'sueca', province: 'Valencia', aliases: [] },
  { officialName: 'Sumacàrcer', spanishName: 'Sumacárcel', valencianName: 'Sumacàrcer', slug: 'sumacarcer', province: 'Valencia', aliases: ['Sumacárcel'] },
  { officialName: 'Tavernes Blanques', spanishName: 'Tabernes Blanques', valencianName: 'Tavernes Blanques', slug: 'tavernes-blanques', province: 'Valencia', aliases: ['Tabernes Blanques'] },
  { officialName: 'Tavernes de la Valldigna', spanishName: 'Tabernes de Valldigna', valencianName: 'Tavernes de la Valldigna', slug: 'tavernes-de-la-valldigna', province: 'Valencia', aliases: ['Tabernes de Valldigna'] },
  { officialName: 'Teresa de Cofrents', spanishName: 'Teresa de Cofrentes', valencianName: 'Teresa de Cofrents', slug: 'teresa-de-cofrents', province: 'Valencia', aliases: ['Teresa de Cofrentes'] },
  { officialName: 'Terrateig', spanishName: 'Terrateig', valencianName: 'Terrateig', slug: 'terrateig', province: 'Valencia', aliases: [] },
  { officialName: 'Titagües', spanishName: 'Titaguas', valencianName: 'Titagües', slug: 'titagues', province: 'Valencia', aliases: ['Titaguas'] },
  { officialName: 'Torre Baixa', spanishName: 'Torrebaja', valencianName: 'Torre Baixa', slug: 'torre-baixa', province: 'Valencia', aliases: ['Torrebaja'] },
  { officialName: 'Torrella', spanishName: 'Torrella', valencianName: 'Torrella', slug: 'torrella', province: 'Valencia', aliases: [] },
  { officialName: 'Torrent', spanishName: 'Torrente', valencianName: 'Torrent', slug: 'torrent', province: 'Valencia', aliases: ['Torrente'] },
  { officialName: 'Torres Torres', spanishName: 'Torres Torres', valencianName: 'Torres Torres', slug: 'torres-torres', province: 'Valencia', aliases: [] },
  { officialName: 'Tous', spanishName: 'Tous', valencianName: 'Tous', slug: 'tous', province: 'Valencia', aliases: [] },
  { officialName: 'Toixa', spanishName: 'Tuéjar', valencianName: 'Toixa', slug: 'toixa', province: 'Valencia', aliases: ['Tuéjar'] },
  { officialName: 'Torís', spanishName: 'Turís', valencianName: 'Torís', slug: 'toris', province: 'Valencia', aliases: ['Turís'] },
  { officialName: 'Utiel', spanishName: 'Utiel', valencianName: 'Utiel', slug: 'utiel', province: 'Valencia', aliases: [] },
  { officialName: 'València', spanishName: 'Valencia', valencianName: 'València', slug: 'valencia', province: 'Valencia', aliases: ['Valencia'] },
  { officialName: 'Vallada', spanishName: 'Vallada', valencianName: 'Vallada', slug: 'vallada', province: 'Valencia', aliases: [] },
  { officialName: 'Vallanca', spanishName: 'Vallanca', valencianName: 'Vallanca', slug: 'vallanca', province: 'Valencia', aliases: [] },
  { officialName: 'Vallès', spanishName: 'Vallés', valencianName: 'Vallès', slug: 'valles', province: 'Valencia', aliases: ['Vallés'] },
  { officialName: 'Venta del Moro', spanishName: 'Venta del Moro', valencianName: 'Venta del Moro', slug: 'venta-del-moro', province: 'Valencia', aliases: [] },
  { officialName: 'Vilamarxant', spanishName: 'Villamarchante', valencianName: 'Vilamarxant', slug: 'vilamarxant', province: 'Valencia', aliases: ['Villamarchante'] },
  { officialName: 'Vilallonga', spanishName: 'Villalonga', valencianName: 'Vilallonga', slug: 'vilallonga', province: 'Valencia', aliases: ['Villalonga'] },
  { officialName: 'Castelló de la Ribera', spanishName: 'Villanueva de Castellón', valencianName: 'Castelló de la Ribera', slug: 'castello-de-la-ribera', province: 'Valencia', aliases: ['Villanueva de Castellón'] },
  { officialName: 'El Villar', spanishName: 'Villar del Arzobispo', valencianName: 'El Villar', slug: 'el-villar', province: 'Valencia', aliases: ['Villar del Arzobispo'] },
  { officialName: 'Villargordo del Cabriel', spanishName: 'Villargordo del Cabriel', valencianName: 'Villargordo del Cabriel', slug: 'villargordo-del-cabriel', province: 'Valencia', aliases: [] },
  { officialName: 'Vinalesa', spanishName: 'Vinalesa', valencianName: 'Vinalesa', slug: 'vinalesa', province: 'Valencia', aliases: [] },
  { officialName: 'Iàtova', spanishName: 'Yátova', valencianName: 'Iàtova', slug: 'iatova', province: 'Valencia', aliases: ['Yátova'] },
  { officialName: 'La Ièsa', spanishName: 'La Yesa', valencianName: 'La Ièsa', slug: 'la-iesa', province: 'Valencia', aliases: ['La Yesa'] },
  { officialName: 'Zarra', spanishName: 'Zarra', valencianName: 'Zarra', slug: 'zarra', province: 'Valencia', aliases: [] },
]

function normalizeText(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/\s+/g, ' ')
}

function municipalityKeys(m: Municipality): string[] {
  return [m.officialName, m.spanishName, m.valencianName, ...m.aliases].map(normalizeText)
}

/** Coincidencia exacta (tras normalizar) contra el nombre oficial, castellano, valenciano o algún alias. */
export function normalizeMunicipality(input: string): Municipality | null {
  if (!input?.trim()) return null
  const target = normalizeText(input)
  return VALENCIA_MUNICIPALITIES.find((m) => municipalityKeys(m).includes(target)) ?? null
}

/** Resultados de autocompletado: empieza-por primero, luego contiene-a, máx. `limit`. */
export function searchMunicipalities(query: string, limit = 8): Municipality[] {
  const q = normalizeText(query)
  if (!q) return []
  const starts: Municipality[] = []
  const contains: Municipality[] = []
  for (const m of VALENCIA_MUNICIPALITIES) {
    const keys = municipalityKeys(m)
    if (keys.some((k) => k.startsWith(q))) starts.push(m)
    else if (keys.some((k) => k.includes(q))) contains.push(m)
  }
  return [...starts, ...contains].slice(0, limit)
}
